#pragma once
#include <atomina.hpp>
#include "../GameEnums.hpp"

class PlayState: public ATMA::BaseState, public ATMA::NetworkMessageListener
{

    PlayState(): BaseState()
    {
    }
    
    virtual ~PlayState() {}

    /**
     * stub implementation of activate function
     */
    virtual void activate() override
    {
    }

    /**
     * stub implementation of deactivate function
     */
    virtual void deactivate() override
    {
    }

    
    virtual void notify(const std::optional<const unsigned int> &l_id, const ATMA::NetworkMessage &l_e) override 
    {
    }

    /**
     * gets state id
     * @returns state id
     */
    virtual unsigned int getId() const override
    {
        return GameStateType(GameStateEnum::PLAYSTATE);
    }

	
    /**
     * passes window events to be handled by the state
     * @param l_winEvent the event generated by the window
     * @returns whether or not the event was handled
     */
    virtual void handleInput(const ATMA::WindowEvent &l_winEvent)
    {
    }

};