#pragma once
#include <atomina.hpp>
#include "../GameEnums.hpp"

class ServerState: public ATMA::BaseState, public ATMA::ObjectEventListener
{
    ATMA::ATMAContext &ctx = ATMA::ATMAContext::getContext();

    ServerState(): BaseState() {}

    virtual ~ServerState() {}

    /**
     * stub implementation of activate function
     */
    virtual void activate() override
    {
        m_active = true;
    }

    /**
     * stub implementation of deactivate function
     */
    virtual void deactivate() override {}

    virtual void notify(const ATMA::ObjectEventContext &l_e) override
    {
        if(l_e.m_objectEventType != ATMA::ObjectEventType(ATMA::ObjectEvent::Network))
            return;
        unsigned int msgType = l_e.m_properties.getAs<unsigned int>("msgType");
        unsigned int connId = l_e.m_properties.getAs<unsigned int>("connId");
        switch(msgType)
        {
        case static_cast<unsigned int>(ATMA::NetworkMessageEnum::PORT_REQUEST):
            {
                int i = 0;
                std::map<std::string, std::any> msgEntries{};
                for(; i < m_ports.size(); i++)
                {
                    msgEntries["port" + std::to_string(i)] = std::pair<unsigned char, std::any>{
                        ATMA::NetworkMessageValueType(ATMA::NetworkMessageValueEnum::SHORT), (short)-1 // occupied
                    };
                    std::pair<unsigned char, std::any> pair{
                        ATMA::NetworkMessageValueType(ATMA::NetworkMessageValueEnum::SHORT),
                        (short)m_ports.size() // empty
                    };
                    ATMA::Props p{{{"port", pair}}};
                    ATMA::NetworkMessage broadcast{ATMA::NetworkMessageType(ATMA::NetworkMessageEnum::PORT_JOIN), p};
                    ctx.netManager.sendMessage(broadcast, m_ports[i]);
                }
                m_ports.emplace_back(connId);
                msgEntries["port" + std::to_string(i)] = std::pair<unsigned char, std::any>{
                    ATMA::NetworkMessageValueType(ATMA::NetworkMessageValueEnum::SHORT), (short)1 // port to be filled
                };
                ++i;
                for(; i < MAX_PORTS; i++)
                {
                    msgEntries["port" + std::to_string(i)] = std::pair<unsigned char, std::any>{
                        ATMA::NetworkMessageValueType(ATMA::NetworkMessageValueEnum::SHORT), (short)0 // empty
                    };
                }
                ATMA::Props p{msgEntries};
                ATMA_ENGINE_INFO("User has requested port data");
                ATMA::NetworkMessage resp{ATMA::NetworkMessageType(ATMA::NetworkMessageEnum::PORT_RESPONSE), p};
                ctx.netManager.sendMessage(resp, connId);
            }
            break;
        case static_cast<unsigned int>(ATMA::NetworkMessageEnum::STATE_CHANGE):
            {
                ATMA::Props p{
                    {{"state",
                      std::pair<unsigned char, std::any>{
                          ATMA::NetworkMessageValueType(ATMA::NetworkMessageValueEnum::UNSIGNEDINT),
                          l_e.m_properties.getAs<unsigned int>("state")}}}};
                ATMA::NetworkMessage nm{ATMA::NetworkMessageType(ATMA::NetworkMessageEnum::STATE_CHANGE), p};
                ctx.netManager.broadcastMessage(nm);
            }
            break;
        default:
            ATMA_ENGINE_INFO("skipped network message type: {}", msgType);
            break;
        }
    }

    /**
     * gets state id
     * @returns state id
     */
    virtual unsigned int getId() const override
    {
        return GameStateType(GameStateEnum::SERVER);
    }

    /**
     * passes window events to be handled by the state
     * @param l_winEvent the event generated by the window
     * @returns whether or not the event was handled
     */
    virtual void handleInput(const ATMA::WindowEvent &l_winEvent) {}
private:
    static const int MAX_PORTS = 2;
    std::vector<std::optional<unsigned int>> m_ports{};
};